export const twinkle = [
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "0.969",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "1.591",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "2.220",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "2.789",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "3.431",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "4.040",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "4.670",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "5.901",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "6.499",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "7.091",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "7.680",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "8.269",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "8.890",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "9.529",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "10.870",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "11.479",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "12.060",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "12.661",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "13.291",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "13.909",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "14.550",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "15.830",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "16.469",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "17.070",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "17.679",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "18.341",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "18.918",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "19.569",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "20.869",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "21.580",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "22.230",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "22.860",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "23.510",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "24.149",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "24.819",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "26.059",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "26.659",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "27.301",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "27.910",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "28.561",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "29.211",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "29.910",
  },
];
const sunshine = [
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "2.081",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "2.490",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "2.940",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "3.390",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "4.220",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "5.259",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "5.619",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "6.040",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "6.461",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "7.239",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "8.391",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "8.780",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "9.189",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "9.599",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "10.379",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "11.639",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "12.031",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "12.411",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "12.820",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "15.000",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "15.421",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "15.851",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "16.268",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "17.090",
  },
  {
    note: "A",
    octave: "4",
    key: "h",
    hasSharp: true,
    timing: "4",
    time: "18.213",
  },
  {
    note: "G",
    octave: "4",
    key: "g",
    hasSharp: true,
    timing: "4",
    time: "18.611",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "19.008",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "19.412",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "20.190",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "21.589",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "22.001",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "22.399",
  },
  {
    note: "F",
    octave: "4",
    key: "f",
    hasSharp: true,
    timing: "4",
    time: "23.539",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "23.980",
  },
  {
    note: "D",
    octave: "4",
    key: "s",
    hasSharp: true,
    timing: "4",
    time: "24.430",
  },
  {
    note: "E",
    octave: "4",
    key: "d",
    hasSharp: false,
    timing: "4",
    time: "25.301",
  },
  {
    note: "C",
    octave: "4",
    key: "a",
    hasSharp: true,
    timing: "4",
    time: "25.719",
  },
];
export const songList = [
  { title: "Twinkle Twinkle", song: twinkle },
  { title: "London Bridge", song: twinkle },
  { title: "You are my sunshine", song: sunshine },
];
